let a=document.querySelector("#btn1");
let b=document.querySelector("#btn2");
let c=document.querySelector("#btn3")
let d=document.querySelector("#btn4")
let e=document.querySelector("#btn5");
let f=document.querySelector("#btn6")
let g=document.querySelector("#btn7")
let h=document.querySelector("#btn8")
let i=document.querySelector("#btn9")
let j=document.querySelector("#btn10")
let k=document.querySelector("#btn11")
let l=document.querySelector("#btn12")
let m=document.querySelector("#btn13")
let n=document.querySelector("#btn14")
let o=document.querySelector("#btn15")
let p=document.querySelector("#btn16")
let q=document.querySelector("#btn17")
let r=document.querySelector("#btn18")
let s=document.querySelector("#btn19")
let t=document.querySelector("#btn20")
let input=document.querySelector("#input1")
a.addEventListener("click",()=>{input.value=''})
b.addEventListener("click",()=>{input.value=input.value.substr(0,input.value.length-1)})
c.addEventListener("click",()=>{input.value+='%'})
d.addEventListener("click",()=>{input.value+='/'})
e.addEventListener("click",()=>{input.value+='7'});
f.addEventListener("click",()=>{input.value+='8'})
g.addEventListener("click",()=>{input.value+='9'})
h.addEventListener("click",()=>{input.value+='/'})
i.addEventListener("click",()=>{input.value+='4'})
j.addEventListener("click",()=>{input.value+='5'})
k.addEventListener("click",()=>{input.value+='6'})
l.addEventListener("click",()=>{input.value+='*'})
m.addEventListener("click",()=>{input.value+='1'})
n.addEventListener("click",()=>{input.value+='2'})
o.addEventListener("click",()=>{input.value+='3'})
p.addEventListener("click",()=>{input.value+='-'})
q.addEventListener("click",()=>{input.value+="0"})
r.addEventListener("click",()=>{input.value+='.'})
s.addEventListener("click",()=>{input.value+='+'})
t.addEventListener("click",()=>{input.value=eval(input.value)})

